<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book a call_insent-popup-card-close-icon</name>
   <tag></tag>
   <elementGuidId>df2795a9-2b2d-4424-9749-868561929b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='insent-popup-card-close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4167b7b2-d163-4bf1-9fc1-8f77ce30664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insent-popup-card-close-icon</value>
      <webElementGuid>780f87c7-f34a-410b-9511-c9e8d0039e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/close.ec75d473.svg</value>
      <webElementGuid>f6e604ea-c2e0-4162-95b9-5dbc703fae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cEvuZC gxfXwW</value>
      <webElementGuid>a4c95667-0dba-4da0-9c4a-9332e0e77d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insent-popup-card-close-icon&quot;)</value>
      <webElementGuid>aa0285b0-7b00-4057-897e-fc3805b6bdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/katalon website types of testing/Page_Katalon AI-augmented Test Automation Platform/iframe_concat(id(, , insent-iframe, , ))_in_d2847a</value>
      <webElementGuid>d24e53f3-f8b2-4ad6-b11c-20e7e47d03e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='insent-popup-card-close-icon']</value>
      <webElementGuid>0a18d21f-933d-4d83-963a-dfe3d50de72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-card-close']/img</value>
      <webElementGuid>5570fa84-4c05-4126-a413-91466b07965e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>63cde70d-543e-4825-a96c-f2e4db5c6af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'insent-popup-card-close-icon' and @src = '/static/media/close.ec75d473.svg']</value>
      <webElementGuid>54e48c3a-d83d-49b0-8b9c-f5672225358e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
